### ISSUE TITLE
[bug] Unexpected Conn

### ISSUE THREAD

**Issue by 9bie** [jfjallid/go-smb#12]
I used example for my Project.
```
session, err := smb.NewConnection(options)
defer session.Close()
```
but some time, i got a error.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x17c3a4c]

goroutine 17961 [running]:
github.com/jfjallid/go-smb/smb.(*Connection).Close(0xc000923340)
        C:/Users/my/go/pkg/mod/github.com/jfjallid/go-smb@v0.3.6/smb/session.go:1782 +0x12c
        .....
```
Then i add trhe code
```
session, err := smb.NewConnection(options)
defer function(){
        fmt.Println(session)
        session.Close()
}
```
i got this
```
&{0xc0005945a0 0xc0021135c0 <nil> 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0 0 0 0xc000b0f680 0xc000b0f620 0xc00239ba40 0xc00239baa0 {0 0} <nil> false 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x17c3a4c]

goroutine 17961 [running]:
github.com/jfjallid/go-smb/smb.(*Connection).Close(0xc000923340)
        C:/Users/my/go/pkg/mod/github.com/jfjallid/go-smb@v0.3.6/smb/session.go:1782 +0x12c
```

i think is no judgment for Connection.conn In session.go:Close():1723 if Connection.conn is nil

Can add a checksum for check Conn is not nil?

Although I don’t know yet how conn is nil.

**Comment by jfjallid** [comment]
Thanks for identifying a problem, I'll take a look.

**Comment by jfjallid** [comment]
I think the problem occurs when the tcp connection close before manually ending the session. One reason for this could be the idle timeout period after which a server will close the connection.

I've added a check in release v0.3.7 which should hopefully solve the issue.
